### PR TITLE
OADP-731: Do not partiallyFail backup if stale snapshot is found

### PR DESCRIPTION
**Pull request by eemcmullan**

### CODE REVIEW

**Comment by weshayutin** [comment]
nice, looks good to me, is there a related issue for this that we can paste into the commit msg?

**Comment by shubham-pampattiwar** [comment]
@weshayutin once the PR is merged, afaik the PR title becomes the commit message.

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by weshayutin** [comment]
> @weshayutin once the PR is merged, afaik the PR title becomes the commit message.

@shubham-pampattiwar 
ya.. I should have specified..  is there a jira issue related to this PR.

**Comment by eemcmullan** [comment]
@weshayutin https://issues.redhat.com/browse/OADP-731

**Pull request merged**
